i/6449: Make block toolbar groupable
ckeditor/ckeditor5-ui pull request #554
Opened 2020-04-08 09:45 UTC by panr

### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Allowed the BlockToolbar to group items when there is no place to show them all. Closes ckeditor/ckeditor5#6449.

---

### Additional information

This PR closes ckeditor/ckeditor5#6449 but it is related also to the issue ckeditor/ckeditor5/issues/6570.

2020-04-08 14:37 UTC, oleq commented on src/toolbar/block/blocktoolbar.js
> +	 * Sets block {@link #toolbarView} max-width, based on
```suggestion
	 * Gets the {@link #toolbarView} max-width, based on
```

2020-04-08 14:37 UTC, oleq commented on src/toolbar/block/blocktoolbar.js
> +	 * editable width plus distance between furthest edge of the {@link #buttonView} and the editable.
```suggestion
	 * editable width plus distance between farthest edge of the {@link #buttonView} and the editable.
```

2020-04-08 14:37 UTC, oleq commented on src/toolbar/block/blocktoolbar.js
> +	 * @returns {String} maxWidth A maximum width that toolbar can have, sets in pixels.
```suggestion
	 * @returns {String} maxWidth A maximum width that toolbar can have, in pixels.
```

2020-04-08 14:44 UTC, oleq requested changes
We're only missing docs about enabling/disabling grouping
* here https://ckeditor.com/docs/ckeditor5/latest/features/blocktoolbar.html#configuration
* and here https://ckeditor.com/docs/ckeditor5/latest/api/module_core_editor_editorconfig-EditorConfig.html#member-blockToolbar

2020-04-09 06:23 UTC, panr commented on src/toolbar/block/blocktoolbar.js
> +	 * editable width plus distance between furthest edge of the {@link #buttonView} and the editable.
That's interesting... 🤔

2020-04-09 15:39 UTC, merged